CREATE TYPE public.color AS ENUM
    ('RED', 'BLACK', 'ORANGE');

ALTER TYPE public.color
    OWNER TO postgres;

CREATE TYPE public.difficulty AS ENUM
    ('EASY', 'HARD', 'IMPOSSIBLE');

ALTER TYPE public.difficulty
    OWNER TO postgres;

CREATE TABLE public."user"
(
    login character varying(200) COLLATE pg_catalog."default" NOT NULL,
    password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT user_login_key UNIQUE (login)
)

    TABLESPACE pg_default;

ALTER TABLE public."user"
    OWNER to postgres;

CREATE TABLE public.person
(
    person_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    person_name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    height real,
    passportid text COLLATE pg_catalog."default" NOT NULL,
    hair_color color,
    locationx integer NOT NULL,
    locationy real NOT NULL,
    locationz integer NOT NULL,
    CONSTRAINT person_pkey PRIMARY KEY (person_id),
    CONSTRAINT person_person_name_check CHECK (person_name::text > ''::text),
    CONSTRAINT person_height_check CHECK (height > 0::double precision),
    CONSTRAINT person_passportid_check CHECK (char_length(passportid) > 8)
)

    TABLESPACE pg_default;

ALTER TABLE public.person
    OWNER to postgres;

CREATE TABLE public.labwork
(
    labwork_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    labwork_name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    coordinatex bigint NOT NULL,
    coordinatey real NOT NULL,
    creationdate timestamp without time zone NOT NULL,
    minimalpoint integer,
    description character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    tunedinworks integer,
    difficulty difficulty NOT NULL,
    person_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT labwork_pkey PRIMARY KEY (labwork_id),
    CONSTRAINT person_id_pkey FOREIGN KEY (person_id)
        REFERENCES public.person (person_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT labwork_labwork_name_check CHECK (labwork_name::text > ''::text),
    CONSTRAINT labwork_coordinatex_check CHECK (coordinatex < 626),
    CONSTRAINT labwork_minimalpoint_check CHECK (minimalpoint > 0),
    CONSTRAINT labwork_description_check CHECK (description::text > ''::text)
)

    TABLESPACE pg_default;

ALTER TABLE public.labwork
    OWNER to postgres;

CREATE INDEX fki_persod_id_pkey
    ON public.labwork USING btree
    (person_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX fki_user_id_fkey
    ON public.labwork USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;
