-- Table: public.labwork

-- DROP TABLE public.labwork;

CREATE TABLE public.labwork
(
    labwork_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    labwork_name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    coordinatex bigint NOT NULL,
    coordinatey real NOT NULL,
    creationdate timestamp without time zone NOT NULL,
    minimalpoint integer,
    description character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    tunedinworks integer,
    difficulty difficulty NOT NULL,
    person_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT labwork_pkey PRIMARY KEY (labwork_id),
    CONSTRAINT person_id_pkey FOREIGN KEY (person_id)
        REFERENCES public.person (person_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public."user" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT labwork_labwork_name_check CHECK (labwork_name::text > ''::text),
    CONSTRAINT labwork_coordinatex_check CHECK (coordinatex < 626),
    CONSTRAINT labwork_minimalpoint_check CHECK (minimalpoint > 0),
    CONSTRAINT labwork_description_check CHECK (description::text > ''::text)
)

TABLESPACE pg_default;

ALTER TABLE public.labwork
    OWNER to postgres;
-- Index: fki_persod_id_pkey

-- DROP INDEX public.fki_persod_id_pkey;

CREATE INDEX fki_persod_id_pkey
    ON public.labwork USING btree
    (person_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: fki_user_id_fkey

-- DROP INDEX public.fki_user_id_fkey;

CREATE INDEX fki_user_id_fkey
    ON public.labwork USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;